### ISSUE TITLE
メニューの作成

### ISSUE THREAD

**Issue by sunnytj39** [kumaido/coemi-app#10]
新着占い・カテゴリ・コラム

**Comment by sh1rataki** [comment]
Homeに設置するTabBarを実装します。
パッケージ"React-Navigation"を導入します

**Comment by sh1rataki** [comment]
blanch:add-tab-menu

**Comment by sh1rataki** [comment]
"React-Navigation" のcreateMaterialTopTabNavigatorを使ったのですが、横にスクロールしません！
（項目が増えちゃうとギッチギチになります）

対策考えます。

**Comment by sh1rataki** [comment]
以下のようにすることで、スクロールさせることができるようになりました！やったね！

![2018-06-14 18 56 46](https://user-images.githubusercontent.com/32187364/41405446-bbb96a4e-7004-11e8-8f17-f40b756da669.png)

**Comment by sh1rataki** [comment]
オプションから無限スクロールはできなさそうです。
